version: "3.8"

services:
  db: 
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy